export const subCategories = [
  {
    id: 1,
    name: "Documentos",
    description: "Documentação, carta, comprovantes, fotos e entre outros.",
    image: require("../assets/documentos.png"),
    category: 1,
  },
  {
    id: 2,
    name: "Contatos",
    description: "Empresas, pessoas e telefones importantes.",
    image: require("../assets/contacts.png"),
    category: 1,
  },
  {
    id: 3,
    name: "Taxas",
    description: "Taxas e valores relevantes.",
    image: require("../assets/tax.png"),
    category: 1,
  },
  {
    id: 4,
    name: "Prazos",
    description: "Períodos e datas.",
    image: require("../assets/date.png"),
    category: 1,
  },
  {
    id: 5,
    name: "Bancos",
    description: "Agências e contas bancárias.",
    image: require("../assets/bank.png"),
    category: 2,
  },
  {
    id: 6,
    name: "Cartões",
    description: "Cartões Úteis",
    image: require("../assets/card.png"),
    category: 2,
  },
  {
    id: 7,
    name: "Aplicativos",
    description: "Aplicativos úteis.",
    image: require("../assets/app.png"),
    category: 3,
  },
  {
    id: 8,
    name: "Moradia",
    description: "Dicas de como conseguir e organizar uma moradia.",
    image: require("../assets/house.png"),
    category: 3,
  },
  {
    id: 9,
    name: "Transporte",
    description: "Locomoção e transportes públicos.",
    image: require("../assets/bus.png"),
    category: 3,
  },
  {
    id: 10,
    name: "Vantagens Estudantes",
    description: "Descontos, cortesias, dicas vantajosas.",
    image: require("../assets/vant.png"),
    category: 3,
  },
  {
    id: 11,
    name: "Saúde",
    description: "Obrigatoriedade, cobertura, assistência e entre outros.",
    image: require("../assets/ambulance.png"),
    category: 4,
  },
  {
    id: 12,
    name: "Viagem",
    description: "Cancelamento, interrupção, assistência e suporte.",
    image: require("../assets/airplane.png"),
    category: 4,
  },
  {
    id: 13,
    name: "Vida",
    description: "Cobertura, segurança e entre outros.",
    image: require("../assets/life.png"),
    category: 4,
  },
  {
    id: 14,
    name: "Créditos",
    description: "Transferência, obtenção e necessidade.",
    image: require("../assets/checklist.png"),
    category: 5,
  },
  {
    id: 15,
    name: "Carga",
    description: "Requisitos, políticas e organização.",
    image: require("../assets/clock.png"),
    category: 5,
  },
  {
    id: 16,
    name: "Equivalência",
    description: "Avaliação de conteúdo, comparação de currículos.",
    image: require("../assets/balance.png"),
    category: 5,
  },
];
